# Generated by Django 5.2.7 on 2025-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_status_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
